#Mimi Trinh
library(rJava)
library(readr)
library(pbkrtest)
library(car)
library(leaps)
library(MASS)
library(xlsxjars)
library(xlsx)
library(corrplot)
library(moments)
library(stats4)
library(rpart)
library(rpart.plot)
setwd('/Users/mimitrinh/Desktop')
moneyball=read.csv('moneyball.csv',header=T)
str(moneyball)
summary(moneyball)
#there are 6 variables with missing values
#no need to address issue with TEAM_BATTING_HBP b/c it has 92% missing value, so it's useless
#only 5 variables left with missing values
complete1=moneyball[3:7]
complete2=moneyball[12:14]
complete3=moneyball[16]
complete=data.frame(c(complete1,complete2,complete3))
str(complete)

#missing value TEAM_BATTING_SO
tree1=data.frame(c(moneyball[8],complete))
summary(tree1)
str(tree1)
fit1=rpart(tree1$TEAM_BATTING_SO~.,method='anova',data=tree1)
printcp(fit1)
summary(fit1)
par(mfrow=c(1,1))
plotcp(fit1)
par(mfrow=c(1,2))
rsq.rpart(fit1)
par(mfrow=c(1,1),xpd=NA) #set xpd=NA here to avoid the plot getting cut off at the end
plot(fit1,uniform=TRUE,main='Regression Tree TEAM_BATTING_SO')
text(fit1,use.n=TRUE,all=TRUE,cex=0.9)
rpart.plot(fit1)

#missing value TEAM_BASERUN_SB
tree2=data.frame(c(moneyball[9],complete))
summary(tree2)
str(tree2)
fit2=rpart(tree2$TEAM_BASERUN_SB~.,method='anova',data=tree2)
printcp(fit2)
summary(fit2)
par(mfrow=c(1,1))
plotcp(fit2)
par(mfrow=c(1,2))
rsq.rpart(fit2)
par(mfrow=c(1,1),xpd=NA)
plot(fit2,uniform=TRUE,main='Regression Tree TEAM_BASERUN_SB')
text(fit2,use.n=TRUE,all=TRUE,cex=0.9)
rpart.plot(fit2)

#missing value TEAM_BASERUN_CS
tree3=data.frame(c(moneyball[10],complete))
summary(tree3)
str(tree3)
fit3=rpart(tree3$TEAM_BASERUN_CS~.,method='anova',data=tree3)
printcp(fit3)
summary(fit3)
par(mfrow=c(1,1))
plotcp(fit3)
par(mfrow=c(1,2))
rsq.rpart(fit3)
par(mfrow=c(1,1),xpd=NA)
plot(fit3,uniform=TRUE,main='Regression Tree TEAM_BASERUN_CS')
text(fit3,use.n=TRUE,all=TRUE,cex=0.7)
rpart.plot(fit3)

#missing value TEAM_PITCHING_SO
tree4=data.frame(c(moneyball[15],complete))
summary(tree4)
str(tree4)
fit4=rpart(tree4$TEAM_PITCHING_SO~.,method='anova',data=tree4)
printcp(fit4)
summary(fit4)
par(mfrow=c(1,1))
plotcp(fit4)
par(mfrow=c(1,2))
rsq.rpart(fit4)
par(mfrow=c(1,1),xpd=NA)
plot(fit4,uniform=TRUE,main='Regression Tree TEAM_PITCHING_SO')
text(fit4,use.n=TRUE,all=TRUE,cex=0.7)
rpart.plot(fit4)

#missing value TEAM_FIELDING_DP
tree5=data.frame(c(moneyball[17],complete))
summary(tree5)
str(tree5)
fit5=rpart(tree5$TEAM_FIELDING_DP~.,method='anova',data=tree5)
printcp(fit5)
summary(fit5)
par(mfrow=c(1,1))
plotcp(fit5)
par(mfrow=c(1,2))
rsq.rpart(fit5)
par(mfrow=c(1,1),xpd=NA)
plot(fit5,uniform=TRUE,main='Regression Tree TEAM_FIELDING_DP')
text(fit5,use.n=TRUE,all=TRUE,cex=0.7)
rpart.plot(fit5)

#predict TARGET_WINS
fit=rpart(moneyball$TARGET_WINS~.,method='anova',data=moneyball)
printcp(fit)
summary(fit)
par(mfrow=c(1,1))
plotcp(fit)
par(mfrow=c(1,2))
rsq.rpart(fit)
par(mfrow=c(1,1),xpd=NA)
plot(fit,uniform=TRUE,main='Regression Tree TARGET_WINS')
text(fit,use.n=TRUE,all=TRUE,cex=0.7)
rpart.plot(fit)


